Crypto provider
skbkontur/extern-csharp-sdk pull request #2
Opened 2020-11-30 13:09 UTC by GangBoss

Crypto provider that allows to Sign Decrypt GetCertificates and VerifySignature

2021-01-11 10:21 UTC, RuslanGatin requested changes

2021-01-11 10:21 UTC, RuslanGatin commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/CryptoExtension.cs
> +    public static class BytesExtension
Лучше бы файл и класс назвать одинаково

2021-01-11 10:21 UTC, RuslanGatin commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/CryptoExtension.cs
> +        public static string GetBase64(this X509Certificate2 cert)
Этот метод будет где-то использоваться?

2021-01-11 10:21 UTC, RuslanGatin commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/WinApiCrypt.cs
> +    internal class WinApiCrypt : ICrypt
Можно публичным, наверно, сделать. Может кто-то из пользователей захочет создавать объекты этого класса

2021-01-11 10:21 UTC, RuslanGatin commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/ICrypt.cs
> +        /// <param name="userLocalSystemStorage">Флаг отвечающий за использование хранилища пользователя или хранилище local_machine </param>
Здесь и ниже нужно use вместо user

2021-04-16 11:15 UTC, GangBoss commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/CryptoExtension.cs
> +        public static string GetBase64(this X509Certificate2 cert)
Если вдруг понадобится всегда можно вернуть, теперь он есть в истории

2021-04-16 11:16 UTC, GangBoss commented on ExternDotnetSDK/ExternDotnetSDK/Cryptography/WinApiCrypt.cs
> +    internal class WinApiCrypt : ICrypt
Если вдруг понадобится - можно вернуть, теперь он есть в истории

2021-05-31 15:02 UTC, RuslanGatin approved these changes

2021-06-04 10:33 UTC, VeronikaVasilyeva commented on ExternDotnetSDK/ExternDotnetSDK/KeApiClient.cs
> +            CryptoProvider=new WinApiCrypt();
1. Поехало форматирование. Советую настроить, чтобы оно делалось автоматически.
2. CryptoProvider не стоит добавлять в клиента. Он нужен скорее в общем классе SDK типа Engine.  В клиента уже должны улетать подписанные, дешифрованные данные

2021-06-04 10:34 UTC, merged